# Generated by Django 5.1.4 on 2024-12-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='short_desc',
            field=models.CharField(max_length=200, verbose_name='Краткое описание'),
        ),
    ]
